disperse/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('resources/', views.resources, name='resources'),
    path('spots/', views.SpotList.as_view(), name='spot_list'),
    path('spots/<int:pk>/', views.SpotDetail.as_view(), name='spot_detail'),
    path('spots/<int:pk>/update/', views.SpotUpdate.as_view(), name='spot_update'),
    path('spots/<int:pk>/delete/', views.SpotDelete.as_view(), name='spot_delete'),
    path('spots/create/', views.SpotCreate.as_view(), name='spot_create'),
    path('accounts/signup/', views.signup, name='signup'),
    path('spots/<int:spot_id>/add_photo/', views.add_photo, name='add_photo'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# installed Pillow for images
from PIL import Image

# Create your models here.

class Spot(models.Model):
    name = models.CharField(max_length=100)
    zipcode = models.IntegerField()
    description = models.TextField(max_length=300)
    latitude = models.DecimalField(max_digits=10, decimal_places=7)
    longitude = models.DecimalField(max_digits=10, decimal_places=7)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='spot_images', blank=True, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('spot_detail', kwargs={'pk': self.id})

class Photo(models.Model):
    spot = models.ForeignKey(Spot, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='spot_images', blank=True, null=True)
    url = models.URLField(blank=True, null=True)
    
    def __str__(self):
        return f"Photo for: {self.spot.name} - {self.url}"

main_app/forms.py
from django import forms
from .models import Spot

class SpotForm(forms.ModelForm):
    class Meta:
        model = Spot
        fields = ['name', 'description', 'zipcode', 'latitude', 'longitude']

    def clean_latitude(self):
        latitude = self.cleaned_data['latitude']
        if not (-90 <= latitude <= 90):
            raise forms.ValidationError('Latitude must be between -90 and 90 degrees.')
        return latitude

    def clean_longitude(self):
        longitude = self.cleaned_data['longitude']
        if not (-180 <= longitude <= 180):
            raise forms.ValidationError('Longitude must be between -180 and 180 degrees.')
        return longitude

main_app/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView

from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import SpotForm
from .models import Spot, Photo

import uuid
import boto3
import os
import requests
import datetime
import folium

S3_BASE_URL = "https://s3.us-east-2.amazonaws.com/"
BUCKET = 'disperse-sjl'

# Create your views here.
def home(request):
    return render(request, 'home.html')

def resources(request):
    return render(request, 'resources.html')


def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('spot_list')
        else:
            error_message = 'Invalid Signup - Try Again'
    form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form, 'error': error_message})

@login_required
def add_photo(request, spot_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            spot = Spot.objects.get(id=spot_id)
            photo = Photo.objects.create(spot=spot, url=url)
            print(f"Image uploaded to S3 and saved to Spot object with URL: {url}")
        except Exception as error:
            print('Photo Upload Failed')
            print(error)
    return redirect('spot_detail', pk=spot_id)

class SpotList(LoginRequiredMixin, ListView):
    model = Spot
    fields = '__all__'
    template_name = 'spots/spot_list.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)

class SpotDetail(LoginRequiredMixin, DetailView):
    model = Spot
    fields = '__all__'
    template_name = 'spots/spot_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        latitude = self.object.latitude
        longitude = self.object.longitude

        #folium map w/ marker
        map = folium.Map(location=[latitude, longitude], zoom_start=13)

        folium.Marker(
            location=[latitude, longitude],
            popup='Your Location',
            icon=folium.Icon(color='red')
        ).add_to(map)

        context['map'] = map._repr_html_()
        context['MAPBOX_ACCESS_TOKEN'] = os.environ.get('MAPBOX_ACCESS_TOKEN')

        # weather
        api_key = os.getenv('API_KEY')
        zip_code = self.object.zipcode
        url = f"http://api.weatherapi.com/v1/forecast.json?key={api_key}&q={zip_code}&days=3&aqi=no&alerts=no"
        response = requests.get(url)
        data = response.json()

        forecast = []
        for day in data["forecast"]["forecastday"]:
            forecast_day = {}
            forecast_day["date"] = datetime.datetime.strptime(day["date"], "%Y-%m-%d").strftime("%m/%d/%Y")
            print(forecast_day["date"])
            forecast_day["icon"] = day["day"]["condition"]["icon"]
            forecast_day["condition"] = day["day"]["condition"]["text"]
            forecast_day["high"] = day["day"]["maxtemp_f"]
            forecast_day["low"] = day["day"]["mintemp_f"]
            forecast_day["sunrise"] = day["astro"]["sunrise"]
            forecast_day["sunset"] = day["astro"]["sunset"]
            forecast.append(forecast_day)

        context['forecast'] = data["forecast"]["forecastday"]
        return context

        

class SpotUpdate(LoginRequiredMixin, UpdateView):
    model = Spot
    fields = ['name', 'description', 'zipcode', 'latitude', 'longitude']
    template_name = 'spots/spot_form.html'

    def form_valid(self, form):
        form.instance.user = self.request.user 
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'There was an error in your submission. Please check the form and try again.')
        return redirect(self.request.path_info)

class SpotDelete(LoginRequiredMixin, DeleteView):
    model = Spot
    success_url = '/spots/'
    template_name = 'spots/spot_confirm_delete.html'

class SpotCreate(LoginRequiredMixin, CreateView):
    model = Spot
    form_class = SpotForm
    template_name = 'spots/spot_form.html'

    def form_valid(self, form):
        form.instance.user = self.request.user 
        return super().form_valid(form)

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="google-site-verification" content="0eNO2m03J5MkN5caMu7uEkv8kOw2acEn8exlR_KljxM" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Handlee&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css" integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI=" crossorigin=""/>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.9.1/mapbox-gl.css' rel='stylesheet' />
    <script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js" integrity="sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM=" crossorigin=""></script>
    <script src='https://api.mapbox.com/mapbox-gl-js/v2.9.1/mapbox-gl.js'></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% block title %}
    <title>Disperse</title>
    {% endblock %}
</head>
<body>
    <div class="wrapper">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'home' %}">Disperse</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'spot_list' %}">My Spots</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'spot_create' %}">Add A Spot</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'resources' %}">Resources</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Log In</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>   
        <main class="container">
            {% block content %} 
            {% endblock %}
        </main>
        <footer class="footer bg-dark text-light py-3">
            <div class="container">
                <span class="footer-txt">Get Lost In The Right Direction - Disperse © {% now "Y" %}</span>
            </div>
        </footer>
    </div>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}

{% block title %}
<title>Disperse Home</title>
{% endblock %}

{% block content %}
<div class="container">
    {% if user.is_authenticated %}
    <h1 class="user_name" style="margin-top: 2rem">Hey {{user.username}}</h1>
    <div class="home-buttons">
        <a href="{% url 'spot_list' %}">
            <button type="button" class="btn btn-secondary btn-lg btn-block">My Spots</button>
        </a>
        <a href="{% url 'spot_create' %}">
            <button type="button" class="btn btn-secondary btn-lg btn-block">Add A Spot</button>
        </a>
        <a href="{% url 'resources' %}">
            <button type="button" class="btn btn-secondary btn-lg btn-block">Resources</button>
        </a>
    </div>
    {% else %}
    <h1>Welcome Wildling</h1>
    <div class="home-buttons">
        <a href="{% url 'signup' %}">
            <button type="button" class="btn btn-secondary btn-lg btn-block">Sign Up</button>
        </a>
        <a href="{% url 'login' %}">
            <button type="button" class="btn btn-secondary btn-lg btn-block">Log In</button>
        </a>
    </div>
    {% endif %}
</div>
{% endblock %}

main_app/templates/resources.html
{% extends 'base.html' %}

{% block title %}
<title>Resources</title>
{% endblock %}

{% block content %}

<button class="btn btn-secondary" onclick="history.back()" style="margin: 2rem 0 0 0">Back</button>
<h1 style="padding: 0 0 2rem 0">Resources</h1>
<h6 style="text-align: center">Need some inspiration on cool spots or other useful tools? Check these out.</h6>
<div class="home-buttons">
    <a href="https://nationalparkssupplyco.com/resources/dispersed-camping-guide/" target="_blank">
        <button type="button" class="btn btn-secondary btn-lg btn-block">Beginner's Guide</button>
    </a>
    <a href="https://www.mountaineers.org/blog/how-to-dispersed-camping"target="_blank">
        <button type="button" class="btn btn-secondary btn-lg btn-block">The Mountaineers</button>
    </a>
    <a href="https://www.fs.usda.gov/"target="_blank">
        <button type="button" class="btn btn-secondary btn-lg btn-block">Forest Service</button>
    </a>
    <a href="https://www.blm.gov/programs/recreation/camping"target="_blank">
        <button type="button" class="btn btn-secondary btn-lg btn-block">BLM Info</button>
    </a>
    <a href="https://thedyrt.com/"target="_blank">
        <button type="button" class="btn btn-secondary btn-lg btn-block">the dyrt</button>
    </a>
</div>

{% endblock %}

main_app/templates/spots/spot_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
<title>Are you sure you want to delete {{ object.name }}?</title>
{% endblock %}


{% block content %}
<h1>Are you sure you want to delete {{ object.name }}?</h1>

<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete {{ object.name }}" class="btn btn-secondary">
    <a href="{% url 'spot_detail' object.id %}" class="btn btn-secondary">No - Cancel</a>
</form>
{% endblock %}

main_app/templates/spots/spot_detail.html
{% extends 'base.html' %}

{% block title %}
<title>Spot Detail</title>
{% endblock %}

{% block content %}
<div class="spot-detail">
    <button class="btn btn-secondary" onclick="history.back()" style="margin: 2rem 0 0 0">Back</button>
    <h2 class="spot-title" style="padding: 0 0 2rem 0">{{ spot.name }}</h2>    
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="mx-auto" id="spot-description">
                    <h4 class="spot_description">{{ spot.description }}</h4>
                    <div class="edit-delete-btns">
                        <a href="{% url 'spot_update' spot.id %}">
                            <button type="button" class="btn btn-secondary">Edit</button>
                        </a>
                        <a href="{% url 'spot_delete' spot.id %}">
                            <button type="button" class="btn btn-secondary">Delete</button>
                        </a>
                    </div>                
                </div>            
            </div>
            <div class="col-md-6">
                <div class="mx-auto" id="map" style="width: 20rem; height: 20rem; border-style: solid; border-color: #3a480b;">
                    <script>
                        var spot = {
                            latitude: {{ spot.latitude }},
                            longitude: {{ spot.longitude }},
                            name: '{{ spot.name }}'
                        };
                        // map
                        console.log(spot.longitude)

                        var map = new mapboxgl.Map({
                            container: 'map',
                            style: 'mapbox://styles/mapbox/outdoors-v11',
                            center: [{{ spot.longitude }}, {{ spot.latitude }}],
                            zoom: 12,
                            accessToken: '{{ MAPBOX_ACCESS_TOKEN }}'
                        });

                        map.addControl(new mapboxgl.NavigationControl({
                            position: 'top-right'
                            }));
            
                        // spot marker
                        var marker = new mapboxgl.Marker()
                            .setLngLat([{{ spot.longitude }}, {{ spot.latitude }}])
                            .addTo(map);
            
                        // popup wth spot details
                        var popup = new mapboxgl.Popup()
                            .setHTML('<h3>{{spot.name}}</h3>')
                            .setMaxWidth('300px');
                        marker.setPopup(popup);
                    </script>
                </div>
            </div>
        </div>
    </div>    
    <div class="weather-box">
        <div class="row">
            <h5 class="card-subtitle mb-2">3 Day Forecast</h5>
            {% for day in forecast %}
            <div class="col-sm-4">
                <div class="card" style="height: 13rem; min-width: 10rem; border-style: solid; border-color: #3a480b;">
                    <div class="card-body">
                        <div class="weather-data">
                            <p>{{ day.date }}</p>
                            <p>{{ day.day.condition.text }}</p>
                            <img class="weather-img" src="{{ day.day.condition.icon }}" alt="{{ day.day.condition.text }}">
                            <p>High: {{ day.day.maxtemp_f }}°F</p>
                            <p>Low: {{ day.day.mintemp_f }}°F</p>
                            <p>Sunrise: {{ day.astro.sunrise }}</p>
                            <p>Sunset: {{ day.astro.sunset }}</p>
                        </div>
                    </div>  
                </div>
            </div>
            {% endfor %}
        </div>   
    </div>          
    <div class="photo-section">
        <div class="row">
            <h5 class="card-subtitle mb-2">My Photos</h5>
            {% for photo in spot.photo_set.all %}
            <div class="col-sm-4 mb-3">
                <div class="card photo-upload" style="border-style: solid; border-color: #3a480b; border-width: thin;">
                    <img src="{{ photo.url|safe }}" alt="{{ spot.name }}" class="card-img-top">
                </div>
            </div>
            {% empty %}
        </div>
        <div class="row">
            <h5 class="card-subtitle mb-2" id="no-photo-box">Upload a Photo Below</h5>
        </div>
        {% endfor %}
    </div>
    <form 
        action="{% url 'add_photo' spot.id %}" 
        method="POST" 
        class="card-panel" 
        enctype="multipart/form-data"
    >
        {% csrf_token %}
        <input type="file" name="photo-file">
        <input class="btn btn-secondary" type="submit" value="Upload Photo">
    </form>
</div>
{% endblock %}

main_app/templates/spots/spot_form.html
{% extends 'base.html' %}

{% block title %}
    {% if object %}
        <title>Update {{ object.name }}</title>
    {% else %}
        <title>Add a Spot</title>
    {% endif %}
{% endblock %}

{% block content %}
<button class="btn btn-secondary" onclick="history.back()" style="margin: 2rem 0 0 0">Back</button>
{% if object %}
    <h1 style="padding: 0 0 2rem 0">Update {{ object.name }}</h1>
{% else %}
    <h1 style="padding: 0 0 2rem 0">Add A New Spot</h1>
{% endif %}

<form method="POST" class="form">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <h6 style="background-color: rgba(233, 233, 234, 0.7); max-width: 12rem">Not at your spot? Enter lat/long above.</h6>
            </td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td><br></td>
            <td></td>
        </tr>
        <tr>
            <td></td>
            <td>
                <h6 style="background-color: rgba(233, 233, 234, 0.7); max-width: 8rem">At your spot?</h6>                   
                <button id="find-location-btn" class="btn btn-secondary">Find My Location</button>
            </td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td><br></td>
            <td></td>
        </tr>
    </table>
    <input type="submit" value="Submit" class="btn btn-secondary">
</form>

<script>
    const findLocationBtn = document.querySelector('#find-location-btn');

    findLocationBtn.addEventListener('click', (event) => {
        event.preventDefault();

        if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(
            (position) => {
                const latitudeField = document.querySelector('#id_latitude');
                const longitudeField = document.querySelector('#id_longitude');
                latitudeField.value = position.coords.latitude.toFixed(7);
                longitudeField.value = position.coords.longitude.toFixed(7);
            },
            (error) => {
                if (error.code === error.PERMISSION_DENIED) {
                    alert('Geolocation access was denied by the user, please enter manually.');
                } else {
                    console.error('Error getting geolocation:', error);
                    alert('Error getting geolocation. Please try again or check your browser settings.');
                }
            }
        );
    } else {
        alert('Geolocation is not supported by your browser.');
    }
});
</script>
{% endblock %}

main_app/templates/spots/spot_list.html
{% extends 'base.html' %}

{% block title %}
<title>Spot List</title>
{% endblock %}

{% block content %}
<button class="btn btn-secondary" onclick="history.back()" style="margin: 2rem 0 0 0">Back</button>
<h1 style="padding: 0 0 2rem 0">My Spots</h1> 
{% if object_list %}
<div class="row">
    {% for spot in object_list %}   
    <div class="col-sm-6" id="spot-card">
        <div class="card my-3">
            <div class="card-body spot-list-cards">
                <h4 class="card-title">{{spot.name}}</h4>
                <a href="{% url 'spot_detail' spot.id %}">
                    {% if spot.photo_set.exists %}
                    <img class="card-img-top img-fluid" src="{{ spot.photo_set.first.url|safe }}" alt="{{ spot.name }}" class="responsive-img card-panel">
                    {% else %}
                    <img class="card-img-top img-fluid" style="object-position: bottom left"src="https://disperse-sjl.s3.us-east-2.amazonaws.com/camping_default.webp?v=1" alt="{{ spot.name }}">
                    {% endif %}            
                </a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<div class="text-center">
    <a href="{% url 'spot_create' %}">
      <button type="button" class="btn btn-secondary btn-lg">Add A Spot</button>
    </a>
</div>
{% else %}
<div class="home-buttons">
    <div class="no_spots">
        <h2>Welcome {{user.username}}!</h2>
        <h3>Let's start tracking your favorite camping locations!</h3>
        <h3></h3>
        <a href="{% url 'spot_create' %}">
            <button type="button" class="btn btn-secondary btn-lg btn-block">Add Your First Spot</button>
        </a>
    </div>
</div>
{% endif %}

{% endblock %}